### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by 2vim** [DevJakey/roblox-authentication-bot#1]
How would one upload the express part to anything, I'm not the best with servers and since you made this I would think you would know the best

**Comment by stranzero** [comment]
Express is used to basically host things on nodejs projects for example apis. It is recommended to buy a domain from somewhere like namecheap and then dns it with cloudflare. After you have done that you should setup your server and point your domain to your localhost. Then use your domain for the rest.

**Comment by 2vim** [comment]
how would i point my domain to localhost?

**Comment by DevJakey** [comment]
Use cloudflare and point it to the local host ip so get the ip of localhost and then you should point it to that.On 11 Jul 2023, at 14:07, rofl ***@***.***> wrote:﻿
how would i point my domain to localhost?

**Comment by stranzero** [comment]
Use cloudflare and point it to the local host ip so get the ip of localhost and then you should point it to that.

**Comment by 2vim** [comment]
i’ve done all of this but it’s not https, and i don’t understand why SSL just isn’t working for the subdomain so as far as i’ve got i cannot add the uri to roblox yet

**Comment by stranzero** [comment]
![image](https://github.com/DevJakey/roblox-authentication-bot/assets/62852156/c8363f99-711c-4630-ba37-7230edb9c877)

**Comment by 2vim** [comment]
yeah its on that

**Comment by stranzero** [comment]
can you add me on discord jakv.

**Comment by 2vim** [comment]
i already have last night haha

**Comment by stranzero** [comment]
can u message me as i got no clue who you are.

**Comment by 2vim** [comment]
we have no mutual servers but my discord is legacyrofl

**Comment by stranzero** [comment]
resolved
